CREATE students(
    id INT PRIMARY KEY AUTO,
    name VARCHAR(10) NOT NULL,
    surname VARCHAR(30) NOT NULL,
    FOREIGN KEY (group_id) REFERENCES groups (id) ON UPDATE CASCADE ON DELETE NULL
);

CREATE proffessors(
    id INT PRIMARY KEY AUTO,
    name VARCHAR(10) NOT NULL,
    surname VARCHAR(30) NOT NULL
);

CREATE groups(
    id INT PRIMARY KEY AUTO,
    name VARCHAR(10) NOT NULL
);

CREATE subjects(
    id INT PRIMARY KEY AUTO,
    title VARCHAR(30) NOT NULL,
    FOREIGN KEY (proffesor_id) REFERENCES proffesors (id) ON UPDATE CASCADE ON DELETE NULL
);

CREATE marks(
    id INT PRIMARY KEY AUTO,
    FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (proffesor_id) REFERENCES proffessors (id) ON DELETE CASCADE ON UPDATE CASCADE,
    mark TINYINT NOT NULL,
    set_at DATETIME DEFAULT CURRENT_DATETIME
)